### ISSUE TITLE
Flashing the CM4

### ISSUE THREAD

**Issue by nilay994** [gumstix/PKG900000001531#1]
Thanks for the nice board @Gumstix!

Questions related to getting started with the Gumstix Raspberry Pi CM4:

1. Can the eMMC of CM4 be flashed directly after being mounted to the Gumstix Board? In other words, can the USB-C connector of the gumstix disable the eMMC boot and force the RPi to boot in the flashing mode?
2. I see "This USB to UART converter connects a host machine from 3-Port USB Client Hub (4) to UART0 on Raspberry Pi CM4 Connector (7)." Is this dependent on the three positions that a switch can be in, next to the USB hub? The USB hub looks really nice, since it exposes multiple UARTs of the STM and RPi at one port. Could there be more verbose statements about the USB hub? Would love to be able to use this multi-channel functionality more frequently.
3. Can there be more verbose documentation of the connection between the STM32 and the CM4? Are these interfaces completely accessible to the user? or are they locked by some application running on the CM4? 
4. What is the difference between the RPi image provided [here](https://github.com/gumstix/PKG900000001531/blob/master/firmware/firmware.md) and the default image? Is it just the device tree reference file?

**Comment by patrickpoirier51** [comment]
Hello,

Funny, I received the board last week and stated working on this by the time you opened issue :-)...
I loaded the UBUNTU image using the Compute Module IO board and it worke flawlessly.
It is mapping  a com port on the USB c and output MAVLINK @ 57600bps

Hope it helps

**Comment by smithandrewc** [comment]
> Thanks for the nice board @gumstix!
> 
> Questions related to getting started with the Gumstix Raspberry Pi CM4:
> 
> 1. Can the eMMC of CM4 be flashed directly after being mounted to the Gumstix Board? In other words, can the USB-C connector of the gumstix disable the eMMC boot and force the RPi to boot in the flashing mode?

Not on this version.  We're building a new version of the board that will allow this.

> 2. I see "This USB to UART converter connects a host machine from 3-Port USB Client Hub (4) to UART0 on Raspberry Pi CM4 Connector (7)." Is this dependent on the three positions that a switch can be in, next to the USB hub? The USB hub looks really nice, since it exposes multiple UARTs of the STM and RPi at one port. Could there be more verbose statements about the USB hub? Would love to be able to use this multi-channel functionality more frequently.

This module puts out the default (UART0) console through an FTDI USB-UART port and is connected to the USB hub, accessible through the Type-C connector.  No switches are necessary, the CM4 console, FMU console and FMU USB bus are all available through the Type-C connector.

> 3. Can there be more verbose documentation of the connection between the STM32 and the CM4? Are these interfaces completely accessible to the user? or are they locked by some application running on the CM4?

The schematic for the board is available here, what additional documentation do you require?  The CM4 and STM32 are connected through a UART channel only (the default TELEM2 channel on FMU).

> 4. What is the difference between the RPi image provided [here](https://github.com/gumstix/PKG900000001531/blob/master/firmware/firmware.md) and the default image? Is it just the device tree reference file?

What "default image" are you referring to?

**Comment by nilay994** [comment]
Thanks so much for the reply on this :rocket: 

> The CM4 and STM32 are connected through a UART channel only (the default TELEM2 channel on FMU).

The USB-C hub is nice and versatile :) Found the channel in the schematics pdf, thank you for providing the reference. Planning to tap into these UART lines serving as a test point, can solder wires on to the 0R resistor. 

> What "default image" are you referring to?

I could have been clearer. With default image, I meant the Raspberry Pi OS/Raspbian or the image that RPi flashing tool uses for getting started with the CM4.
