### ISSUE TITLE
UBUNTU source & framework

### ISSUE THREAD

**Issue by patrickpoirier51** [gumstix/PKG900000001531#2]
Hello, 

I just loaded the UBUNTU image and it work ok with PX4.

My goal is to make an image for ArduPilot and not wanting to reinvent the wheel, I would need detailled information on the different modules used (if any), specific mappings of peripherals, config files and startup scripts.

Regards

**Comment by patrickpoirier51** [comment]
Well... in the meantime I think I'll dig into it ;-)

--First issue Pi is not showing on third USB mapping

I could see Mavlink on first USB and PX4 Shell on second USB, but no RPI login on third.
Her's what I dis to correct:

`/boot/firmware/config.txt
enable_uart=1 


/boot/firmware/syscfg.txt
#cmdline=cmdline.txt
cmdline=cmdline.txt.serial

at cmdline.txt.serial
net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc

remove symlink on rc.local == I want a direct link to the port 
cat rc.local
#!/bin/bash
#ln -s /dev/ttyAMA1 /dev/ttyS0
`

-- 

Then ENABLE WIFI
ENABLE WIFI
https://linuxconfig.org/ubuntu-20-04-connect-to-wifi-from-command-line

ENABLE SSH
https://linuxize.com/post/how-to-enable-ssh-on-ubuntu-20-04/

reboot then  ssh ubuntu on WIFI address  with raspberry as password


now we have access to internet and  we can update , add tools ... whatever
 !!! Issue while building packages = 
`update-initramfs: Generating /boot/initrd.img-5.4.0-1021-raspi
Unsupported platform.
run-parts: /etc/initramfs/post-update.d//flash-kernel exited with return code 1
dpkg: error processing package initramfs-tools (--configure):
 installed initramfs-tools package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 initramfs-tools
`

But the installed packages seems to work ok ... so far :-)


Finally install MAVPROXY

Install MAVPROXY
pip install PyYAML mavproxy --user

echo "export PATH=$PATH:$HOME/.local/bin" >> ~/.bashrc
source ~/.bashrc

 mavproxy.py --master=/dev/ttyAMA1 --baudrate=921600 --out=udpout: "toGCS:14550

Enjoy,  Regards

**Comment by smithandrewc** [comment]
> Hello,
> 
> I just loaded the UBUNTU image and it work ok with PX4.
> 
> My goal is to make an image for ArduPilot and not wanting to reinvent the wheel, I would need detailled information on the different modules used (if any), specific mappings of peripherals, config files and startup scripts.
> 
> Regards

Autopilot was built to conform to Pixhawk FMUv6U standard. Spec should have been published by now but I don't see it. All board support has been added to mainline PX4. All hardware documents have been uploaded here.

What else are you looking for?

**Comment by smithandrewc** [comment]
> Well... in the meantime I think I'll dig into it ;-)
> 
> --First issue Pi is not showing on third USB mapping
> 
> I could see Mavlink on first USB and PX4 Shell on second USB, but no RPI login on third.
> Her's what I dis to correct:
> 
> `/boot/firmware/config.txt
> enable_uart=1
> 
> /boot/firmware/syscfg.txt
> #cmdline=cmdline.txt
> cmdline=cmdline.txt.serial
> 
> at cmdline.txt.serial
> net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc
> 
> remove symlink on rc.local == I want a direct link to the port
> cat rc.local
> #!/bin/bash
> #ln -s /dev/ttyAMA1 /dev/ttyS0
> `
> 
> --
> 
> Then ENABLE WIFI
> ENABLE WIFI
> https://linuxconfig.org/ubuntu-20-04-connect-to-wifi-from-command-line
> 
> ENABLE SSH
> https://linuxize.com/post/how-to-enable-ssh-on-ubuntu-20-04/
> 
> reboot then ssh ubuntu on WIFI address with raspberry as password
> 
> now we have access to internet and we can update , add tools ... whatever
> !!! Issue while building packages =
> `update-initramfs: Generating /boot/initrd.img-5.4.0-1021-raspi Unsupported platform. run-parts: /etc/initramfs/post-update.d//flash-kernel exited with return code 1 dpkg: error processing package initramfs-tools (--configure): installed initramfs-tools package post-installation script subprocess returned error exit status 1 Errors were encountered while processing: initramfs-tools `
> 
> But the installed packages seems to work ok ... so far :-)
> 
> Finally install MAVPROXY
> 
> Install MAVPROXY
> pip install PyYAML mavproxy --user
> 
> echo "export PATH=$PATH:$HOME/.local/bin" >> ~/.bashrc
> source ~/.bashrc
> 
> mavproxy.py --master=/dev/ttyAMA1 --baudrate=921600 --out=udpout: "toGCS:14550
> 
> Enjoy, Regards

I believe only change required to get console is setting enable_uart=1.

Have you tried mainline Raspberry Pi OS? That works as well.

**Comment by patrickpoirier51** [comment]
Hello,

Thanks for getting back so rapidly :-)

Concerning uart access , is this mapping  really required then ?
ln -s /dev/ttyAMA1 /dev/ttyS0

Has the mainline Raspberry Pi OS has access to the CORAL chip ?

Regards,

**Comment by smithandrewc** [comment]
I don't see why that mapping would be required.

Coral chip is USB, software support is identical to USB Accelerator 

https://coral.ai/docs/accelerator/get-started/

**Comment by patrickpoirier51** [comment]
Ahhh cool , I thought it was deeply interconnected with PCI bus as described here:
**Gumstix Raspberry Pi CM4 + Pixhawk FMUv6   page 8** 

The module connects to the following buses:
• PCIE nCLKREQ to PCIE CLKREQ on Raspberry Pi CM4 Connector (7)
• VLOGIC PCIE CTRL to VLOGIC on Raspberry Pi CM4 Connector (7)
• PCIe to PCIE on Raspberry Pi CM4 Connector (7)

![image](https://user-images.githubusercontent.com/12484190/112910754-12e53b00-90c2-11eb-9fc6-a9019214dfaf.png)

**Comment by patrickpoirier51** [comment]
and lsusb doe not show much

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
ubuntu@ubuntu:~$ Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by patrickpoirier51** [comment]
OK, double check with schematic and yeah.... it is USB only

![image](https://user-images.githubusercontent.com/12484190/112971819-984a0900-911d-11eb-9acb-62fe6870d55c.png)

**Comment by patrickpoirier51** [comment]
@smithandrewc  I think the documentation would  need to be more explicit....
Now question: How do we access the TPU ?

**Comment by patrickpoirier51** [comment]
I cannot see the Google Coral on the Gumstix
It works OK on the CM IO Board with a CORAL stick plugged in USB

Any guidance ?

**Comment by smithandrewc** [comment]
Early test boards had an issue with the Coral device, we've addressed it in our newest build.

**Comment by patrickpoirier51** [comment]
@smithandrewc  there are other issues in this thread, I guess you will fix that ?

One other thing
it looks like you somehow installed an older version of tflite_runtime, the version should have returned 2.5:
python3 -c 'print(__import__("tflite_runtime").__version__)'
2.5.0

sudo pip3 remove tflite-runtime == it was 2.1
and reinstall with apt

**Comment by smithandrewc** [comment]
What other issues? This Ubuntu image is the original one we deployed with the CM4 before there was mainline support. I would recommend using a new image. We will be removing this image soon.

**Comment by patrickpoirier51** [comment]
The nonexistent  mapping of the Pi  console on USB
The outdated python library
The misguiding documentation

An I might add
The undocumented method to flash the firmware
The lack of transparence on a major issue with the Beta Units, as I am still thinking if  shorted data lines might damage  the CM4 USB circuitry 

Regards,

**Comment by smithandrewc** [comment]
> The nonexistent mapping of the Pi console on USB

I don't understand this, UART0 is the standard console port.  On all Raspberry Pi OS images, it's enabled by setting "enable_uart=1" or raspi-config

https://www.raspberrypi.org/documentation/configuration/uart.md

> The outdated python library 

As I said, this is an old image we used for development.  A current Raspberry Pi OS image would be a better starting point.  I will be removing this firmware link soon.

> The misguiding documentation 

Could you elaborate please?

> An I might add The undocumented method to flash the firmware.

Flashing the CM4 is well documented 

https://www.raspberrypi.org/documentation/hardware/computemodule/cm-emmc-flashing.md

Not every board is capable of flashing a CM4 (just like other CMx modules).  That is why we make dedicated CMx flashing boards.  The CM4 has a single USB OTG port.  On this board we're using in host mode so it's not available as a device (to flash).

**Comment by patrickpoirier51** [comment]
I mean flashing the firmware on the STM32 

As for the misleading information 
This is misleading as the final design is purely USB

> Ahhh cool , I thought it was deeply interconnected with PCI bus as described here:
> **Gumstix Raspberry Pi CM4 + Pixhawk FMUv6 page 8**
> 
> The module connects to the following buses:
> • PCIE nCLKREQ to PCIE CLKREQ on Raspberry Pi CM4 Connector (7)
> • VLOGIC PCIE CTRL to VLOGIC on Raspberry Pi CM4 Connector (7)
> • PCIe to PCIE on Raspberry Pi CM4 Connector (7)
> 
> ![image](https://user-images.githubusercontent.com/12484190/112910754-12e53b00-90c2-11eb-9fc6-a9019214dfaf.png)

**Comment by smithandrewc** [comment]
> I mean flashing the firmware on the STM32

This is a mainline supported PX4 board.  Flashing it follows the same routine as all the other PX4 boards (QGroundcontrol or via source code). 

> 
> As for the misleading information
> This is misleading as the final design is purely USB
> 
> > Ahhh cool , I thought it was deeply interconnected with PCI bus as described here:
> > **Gumstix Raspberry Pi CM4 + Pixhawk FMUv6 page 8**
> > The module connects to the following buses:
> > • PCIE nCLKREQ to PCIE CLKREQ on Raspberry Pi CM4 Connector (7)
> > • VLOGIC PCIE CTRL to VLOGIC on Raspberry Pi CM4 Connector (7)
> > • PCIe to PCIE on Raspberry Pi CM4 Connector (7)
> > ![image](https://user-images.githubusercontent.com/12484190/112910754-12e53b00-90c2-11eb-9fc6-a9019214dfaf.png)

This is a good point, that is confusing.  We'll fix it, thanks for pointing it out.

**Comment by patrickpoirier51** [comment]
You are welcome :-)
