### ISSUE TITLE
PX4 firmware hex / binary file

### ISSUE THREAD

**Issue by hwjalapeno** [gumstix/PKG900000001531#5]
Hi,
I am trying to design a new version of Pixhawk-based board (for which I am thinking of using your baseboard design) for a project, to add jetson nano instead of raspberry pi, and in my design, I am not sure how you have managed to to provide direct bootloader access to only the pixhawk, so have you already compiled a hex or binary for just PX4, so that atleast I can upload it on JTAG, thanks!

**Comment by CRVARUN** [comment]
Follow-up question, do I have to download a bootloader specific to H7 MCU, and how did you guys compile it? It would be great if we could collaborate on this project together
